name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/TsenterStroySSHKey"
      - run: chmod 600 "$HOME/.ssh/TsenterStroySSHKey"
      # Deploy
      - run: cd BuildingMaterialsStore && rsync -e "ssh -p 20022 -i $HOME/.ssh/TsenterStroySSHKey -o StrictHostKeyChecking=no" --archive --compress --delete . root@5.181.109.10:/home/BuildingMaterialsStore
